public enum EdibleMushrooms {
    ATUS, CRATERELLUS_CORNUCOPIOIDES, FLAMMULINA_VELUTIPES, GRIFOLA_FRONDOSA, GYROMITRA_ESCULENTA, HERICIUM_ERINACEUS, HYDNUM_REPANDUM, HYGROPHORUS_CHRYSODON, LACTARIUS_DELICIOSUS, LECCINUM_VERSIPELLE, MACROLEPIOTA_PROCERA, MORCHELLA_SPECIES, PLEUROTUS_OSTREATUS, SPARASSIS_CRISPA, SUILLUS_BOVINUS, TRICHOLOMA_MATSUTAKE, TUBER_BORCHII;
}
